module.exports = {
  apps: [{
    name: 'promohive',
    script: './dist/index.js',
    instances: 'max',
    exec_mode: 'cluster',
    env: {
      NODE_ENV: 'development',
    },
    env_production: {
      NODE_ENV: 'production',
      PORT: 3002,
      HOST: 'srv1052990.hstgr.cloud',
      DATABASE_URL: 'postgresql://postgres:[YOUR-PASSWORD]@db.jxtutquvxmkrajfvdbab.supabase.co:5432/postgres',
      SUPABASE_URL: 'https://jxtutquvxmkrajfvdbab.supabase.co',
      SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dHV0cXV2eG1rcmFqZnZkYmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NDA5MjcsImV4cCI6MjA3NzAxNjkyN30.jLMQWJqwj6Amja-bsBmLwZjmTHgusL_1q2n_ZThbRrM',
      SUPABASE_SERVICE_ROLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dHV0cXV2eG1rcmFqZnZkYmFiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MTQ0MDkyNywiZXhwIjoyMDc3MDE2OTI3fQ.kWtyqG9Rz7Z_Cf2hBhgjW5eMwPgC6YLJzZQH1gW8D7o',
      JWT_SECRET: 'promohive-super-secret-jwt-key-2024',
      JWT_REFRESH_SECRET: 'promohive-super-secret-refresh-key-2024',
      ACCESS_TOKEN_EXPIRES_IN: '15m',
      REFRESH_TOKEN_EXPIRES_IN: '7d',
      CORS_ORIGIN: 'https://globalpromonetwork.store',
      PLATFORM_URL: 'https://globalpromonetwork.store',
      RATE_LIMIT_WINDOW_MS: '900000',
      RATE_LIMIT_MAX_REQUESTS: '100',
      SMTP_HOST: 'smtp.hostinger.com',
      SMTP_PORT: '465',
      SMTP_SECURE: 'true',
      SMTP_USER: 'promohive@globalpromonetwork.store',
      SMTP_PASS: 'PromoHive@2025!',
      SMTP_FROM: 'promohive@globalpromonetwork.store',
      ADGEM_JWT_SECRET: 'your-adgem-jwt-secret',
      ADSTERRA_API_KEY: 'your-adsterra-api-key',
      CPALEAD_API_KEY: 'your-cpalead-api-key',
      LOG_LEVEL: 'info',
      BCRYPT_SALT_ROUNDS: '12'
    },
    error_file: './logs/pm2-error.log',
    out_file: './logs/pm2-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
  }],
};

